### ISSUE TITLE
Single member case class writes

### ISSUE THREAD

**Issue by graphex** [jto/validation#21]
When my case class has only one property, how do I define the writer?
I am probably missing something obvious, but it seems like an issue because it makes using the API consistently more difficult.
```scala
case class A(x: Int)
implicit val aW = To[JsObject] { __ =>
  import play.api.data.mapping.json.Writes._
  ((__ \ "x").write[Int])(unlift(A.unapply _))
}
```

```
error: type mismatch;
 found   : Option[Int]
 required: Option[play.api.data.mapping.WriteLike[Int,play.api.libs.json.JsObject]]
```

**Comment by jto** [comment]
Hey @graphex did it solve your issue ?

**Comment by graphex** [comment]
I think so... or I forgot if it didn't.
