### ISSUE TITLE
add Write/Rule.apply[I, O](implicit a: Write/Rule[I, O]) = a

### ISSUE THREAD

**Issue by mandubian** [jto/validation#27]

**Comment by jto** [comment]
Unfortunately there's already an `apply` method defined on `Rule` and `Write`. Adding this would create an annoying ambiguity leading to worse type inference. I've introduced `of` in v2.0 instead.  see https://github.com/jto/validation/commit/0166279bf7161b8adee550f38745f0b0cb204011
