### ISSUE TITLE
Is it possible to get a build for Scala 2.10.4?

### ISSUE THREAD

**Issue by graphex** [jto/validation#29]
It looks like Sonatype only has 2.11 builds available, would it be possible for 2.10.4 builds to be published?

**Comment by jto** [comment]
Possibly. The only "hard" part is getting the macros to work I guess. Do you really need it ? If so, PR appreciated ;)

**Comment by stanch** [comment]
Fixed in the linked PR. I would appreciate publishing as well! By the way, I am not sure why you decided not to publish for `2.10` — the only breaking change since last time it was published was in `validation-xml`, but it was easy to fix.

**Comment by jto** [comment]
Closing the issue since it was fixed a long time ago. Thank you for your PR :)
