### ISSUE TITLE
`Rule.compose` really should be named `Rule.andThen`

### ISSUE THREAD

**Issue by julienrf** [jto/validation#41]
See how it is named in [scalaz](https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/Kleisli.scala#L17) or [cats](https://github.com/non/cats/blob/master/core/src/main/scala/cats/data/Kleisli.scala#L36).

That’s really confusing because `compose` usually means combination in the reverse side… (see in [scalaz](https://github.com/non/cats/blob/master/core/src/main/scala/cats/data/Kleisli.scala#L36) or [cats](https://github.com/non/cats/blob/master/core/src/main/scala/cats/data/Kleisli.scala#L42)).

**Comment by jto** [comment]
Fixed in v2.0. Thanks for the feedback :)
