### ISSUE TITLE
Why did you guys use Success/Failure rather than specific names like ValidationSuccess?

### ISSUE THREAD

**Issue by queirozfcom** [jto/validation#45]
You have probably ditched `JsSuccess` as it is in Play because this library is not json-specific anymore, but `Success` and `Failure` conflicts with `scala.util.Try` stuff.

I find myself always needing to alias them to `ValidationSuccess` and `ValidationFailure` so they don't conflict with scala default Try. Am I missing something?

**Comment by jto** [comment]
This problem will be fixed in the soon to be released 2.0 version (see [v2.0 branch](https://github.com/jto/validation/tree/v2.0)). Validation now uses cats' `Valid` / `Invalid`.
