### ISSUE TITLE
Update to Play 2.5

### ISSUE THREAD

**Issue by ottovw** [jto/validation#46]
When are you planning to create a release for play 2.5?

Thanks

**Comment by maxcom** [comment]
see #47

**Comment by cvanfleteren** [comment]
Any ETA on a 2.0 release?

**Comment by jto** [comment]
@OlivierBlanvillain and I are still working on finishing scala.js support for the 2.0 release. Specifically, we're still working on cross compiled rules / writes. There's a [pending PR](https://github.com/jto/validation/pull/62), which is basically the final step before releasing 2.0. As soon as we're satisfied, we'll rel

**Comment by jto** [comment]
I've just published a pre-version of the 2.0 documentation here: http://jto.github.io/validation/docs/book/
Feedbacks are welcome. @OlivierBlanvillain is updating the scala.js docs. We expect to release v2.0 (including play 2.5 support) very soon.
