### ISSUE TITLE
Implicit syntax is automatically added

### ISSUE THREAD

**Issue by julienrf** [jto/validation#48]
Please separate the implicit conversions defined at the package level or in companion objects so that they are not added to the implicit scope automatically. They can cause ambiguous implicit resolutions if the developer already imports, for instance `cats.syntax.cartesian._`.

**Comment by OlivierBlanvillain** [comment]
I did not try using the v2 stuff along with cats and did not notice the issue, thanks for reporting!

**Comment by julienrf** [comment]
Hi, you forgot implicit definitions in companion objects like these: https://github.com/jto/validation/blob/v2.0/validation-core/src/main/scala/Rule.scala#L164-L173

**Comment by OlivierBlanvillain** [comment]
It was intentional, I don't see how these could cause any kind of conflicts (`SyntaxCombine` is completely independent from cats)

**Comment by julienrf** [comment]
Ok, no problem.
