### ISSUE TITLE
Variance

### ISSUE THREAD

**Issue by julienrf** [jto/validation#49]
Could you make `RuleLike[I, O]` and `WriteLike[I, O]` contravariant in `I`, and covariant in `O`?

**Comment by jto** [comment]
I dont' think it would make much sense.

Making `Rule` covariant in `O` means that given 2 types `A` and `B` where `B <: A`, I could pass to any method expecting a `Rule[I, A]` a `Rule[I, B]`. Obviously the `Rule[I, B]` is inadequate. It may for example require the a given attribute specific to `B` to exists in `I`. 

Contravariance in `I` means that if you could pass a `Rule[I', A]` to a method expecting a `Rule[I, A]` if `I' <: I`. It could work for JSON but I think it' hard to tell if it would work for any `I` and `I'`. It's also IMHO a rather uncommon use case so I don't think it's worth the added complexity.

`Write` is already covariant in `O`.

On Write, that means you can use a `Write[A, O]` where a `Write[B, O]` is expected. Obviously you'll be missing fields in `O`. If you try to then "parse" the output with a `Rule[O, B]`, it's going to fail. Is this is really what you want to do, just upcast, but I think it's too dangerous to be the default.

Lastly, introducing variance in validation would introduce ambiguities in implicit resolutions . Consider the following function:

```scala
def foo(implicit Rule[I, B]) = ...
```

If `Rule[I, B]` and `Rule[I, A]` both exists, you have a problem. You obviously know which one is correct, scalac won't.

**Comment by julienrf** [comment]
I actually faced several situations where variance annotations would have helped. The latest I can remind is the following:

~~~ scala
scala> import play.api.data.mapping._
import play.api.data.mapping._

scala> import play.api.libs.json._
import play.api.libs.json._

scala> import play.api.data.mapping.json._
import play.api.data.mapping.json._

scala> import play.api.data.mapping.json.Rules._
import play.api.data.mapping.json.Rules._

scala> val isObject: Rule[JsValue, JsObject] =
     | Rule {
     |   case obj: JsObject => Success(obj)
     |   case _ => Failure(Seq(Path -> Seq(ValidationError("object required"))))
     | }
isObject: play.api.data.mapping.Rule[play.api.libs.json.JsValue,play.api.libs.json.JsObject] = play.api.data.mapping.Rule$$anon$1@6287f56a

scala> val getFoo = From[JsValue] { __ => (__ \ "foo").read[String] }
getFoo: play.api.data.mapping.Rule[play.api.libs.json.JsValue,String] = play.api.data.mapping.Rule$$anon$2@24127b1c
~~~

And then:

~~~ scala
scala> isObject.compose(getFoo)
<console>:25: error: overloaded method value compose with alternatives:
  [P](m: play.api.data.mapping.Mapping[play.api.data.mapping.ValidationError,play.api.libs.json.JsObject,P])play.api.data.mapping.Rule[play.api.libs.json.JsValue,P] <and>
  [P](sub: => play.api.data.mapping.RuleLike[play.api.libs.json.JsObject,P])play.api.data.mapping.Rule[play.api.libs.json.JsValue,P] <and>
  [P](path: play.api.data.mapping.Path)(sub: => play.api.data.mapping.RuleLike[play.api.libs.json.JsObject,P])play.api.data.mapping.Rule[play.api.libs.json.JsValue,P]
 cannot be applied to (play.api.data.mapping.Rule[play.api.libs.json.JsValue,String])
       isObject.compose(getFoo)
                ^
~~~

However (when using arrows that are correctly variance-annotated):

~~~ scala
scala> val isObjectFun: JsValue => JsObject = jsValue => ???
isObjectFun: play.api.libs.json.JsValue => play.api.libs.json.JsObject = <function1>

scala> val getFooFun: JsValue => String = jsValue => ???
getFooFun: play.api.libs.json.JsValue => String = <function1>

scala> isObjectFun.andThen(getFooFun)
res4: play.api.libs.json.JsValue => String = <function1>
~~~

**Comment by jto** [comment]
The example seems convoluted, `getFoo` alone does the job so I don't see why you would use isObject.
On the rare occasions you do need something like that, a simple type annotation is enough to fix the type issue.

Given the problems I already mentioned, and the tiny benefits, this is not going to change. I actually tested this in the early development of the library. It was not a good idea.

**Comment by julienrf** [comment]
> The example seems convoluted, getFoo alone does the job so I don't see why you would use isObject.

The error message will not be the same if I only use `getFoo`.
This example is actually extracted from a real world use case: we want to check that clients effectively send us a JSON object before even trying to pick the fields within it.

> On the rare occasions you do need something like that, a simple type annotation is enough to fix the type issue.

That is still a mess, IMHO:

~~~ scala
// fixes `isObject.compose(getFoo)`
isObject.map(jsObject => jsObject: JsValue).compose(getFoo)
~~~

And the error messages are painful to understand (see above).

> Given the problems I already mentioned,

Actually, I think the problems you mentioned are convoluted.

> Making Rule covariant in O means that given 2 types A and B where B <: A, I could pass to any method expecting a Rule[I, A] a Rule[I, B]. Obviously the Rule[I, B] is inadequate. It may for example require the a given attribute specific to B to exists in I.

Can you give me an actual example of such a situation? Why would you have such a `Rule[I, B]` in scope?

> Contravariance in I means that if you could pass a Rule[I', A] to a method expecting a Rule[I, A] if I' <: I. It could work for JSON but I think it' hard to tell if it would work for any I and I'. It's also IMHO a rather uncommon use case so I don't think it's worth the added complexity.

The situation I described with `isObject.compose(getFoo)` is actually an instance of this case.

> On Write, that means you can use a Write[A, O] where a Write[B, O] is expected. Obviously you'll be missing fields in O. If you try to then "parse" the output with a Rule[O, B], it's going to fail. Is this is really what you want to do, just upcast, but I think it's too dangerous to be the default.

This however very useful to serialize sum types:

~~~ scala
scala> import play.api.data.mapping._
import play.api.data.mapping._

scala> import play.api.libs.json._
import play.api.libs.json._

scala> :paste
// Entering paste mode (ctrl-D to finish)

sealed trait Foo
case object Bar extends Foo
case object Baz extends Foo

object Foo {
  val write: Write[Foo, JsValue] = ???
}

// Exiting paste mode, now interpreting.

<console>:22: warning: dead code following this construct
         val write: Write[Foo, JsValue] = ???
                                          ^
defined trait Foo
defined object Bar
defined object Baz
defined object Foo

scala> def serialize[A](a: A)(implicit w: Write[A, JsValue]): JsValue = w.writes(a)
serialize: [A](a: A)(implicit w: play.api.data.mapping.Write[A,play.api.libs.json.JsValue])play.api.libs.json.JsValue

scala> serialize(Bar)
<console>:21: error: could not find implicit value for parameter w: play.api.data.mapping.Write[Bar.type,play.api.libs.json.JsValue]
       serialize(Bar)
                ^
~~~

If `Write[A, B]` were contravariant in A this problem would not exist.

> Lastly, introducing variance in validation would introduce ambiguities in implicit resolutions . Consider the following function:
>
> ~~~ scala
> def foo(implicit Rule[I, B]) = ...
> ~~~
> If Rule[I, B] and Rule[I, A] both exists, you have a problem. You obviously know which one is correct, scalac won't.

Can you give me an example where you would have such both rules?

BTW, I think that another benefit of adding variance annotations is that you could make your default rules more precise: `intW` could be a `Rule[Int, JsNumber]` rather than a `Rule[Int, JsValue]`, etc. If you try to do that now (without variance annotations) you will have a lot of type errors.

**Comment by julienrf** [comment]
That being said, I do understand that adding variance annotation will also probably add complexity to some method signatures :(

Maybe I’ll give it a try and do a PR if it seems really better. I’ve noticed that several similar projects (e.g. circe’s `Decoder`, cat’s `Profunctor`) have invariant type parameters.

**Comment by jto** [comment]
> Can you give me an actual example of such a situation? Why would you have such a Rule[I, B] in scope?

Because concrete class inheritance is a thing.

> The situation I described with isObject.compose(getFoo) is actually an instance of this case.

You're missing the point. Yes it works for JSON, but this lib is not limited to JSON, and there's no way to tell if it works for any type `I`.

> If Write[A, B] were contravariant in A we would not have the final type error.

The fix is trivial
```scala
 serialize[Foo](Bar)
```

you could also add variance yourself:

```scala
def serialize[A, B, B <: A](a: B)(implicit w: Write[A, JsValue]): JsValue = w.writes(a)
```

 > Can you give me an example where you would have such both rules?

Any project using Scala as an OOP language will end up there.

> BTW, I think that another benefit of adding variance annotations is that you could make your default rules more precise: intW could be a Rule[Int, JsNumber] rather than a Rule[Int, JsValue], etc. If you try to do that now (without variance annotations) you will have a lot of type errors.

That's a fair point, but you also make the application site types less precise. I would argue that you're even loosing precision there.

> Maybe I’ll give it a try and do a PR if it seems really better. I’ve noticed that several similar projects (e.g. circe’s Decoder, cat’s Profunctor) have invariant type parameters, though.

Go on, I'd be happy to see the results. As you imagine I walk down that pass a long time ago. Don't think that it was not a well thought choice.

**Comment by julienrf** [comment]
> Because concrete class inheritance is a thing.

> Any project using Scala as an OOP language will end up there.

Honestly, I think I’ve never seen a project having implicit `Read` or `Write` instances for both `A` and `B` (with `A <: B` or `A >: B`). In practice we either have instances for the leaves or for the root type of a hierarchy, don’t you think?

> The fix is trivial
> 
> ~~~ scala
> serialize[Foo](Bar)
> ~~~
> 
> you could also add variance yourself:
> 
> ~~~ scala
> def serialize[A, B, B <: A](a: B)(implicit w: Write[A, JsValue]): JsValue = w.writes(a)
> ~~~

I know but my feeling is that by doing this I’m finding workarounds, at use-site, for something that should be fixed at definition-site (with variance annotations).

> That's a fair point, but you also make the application site types less precise.

I don’t understand what you mean, could you elaborate please?

**Comment by jto** [comment]
> I don’t understand what you mean, could you elaborate please?

You argue that `Rule[JsValue, Int]` is less precise than `Rule[JsNumber, Int]`, faire enough. But in order to support this you need variance in the call site (where you do implicit resolution), hence you're just moving the problem elsewhere.

**Comment by julienrf** [comment]
No, I was talking about `Write[Int, JsNumber]` vs `Write[Int, JsValue]` :)

**Comment by jto** [comment]
Ok I got confused because you've mentioned `Rule` in the original message:

> BTW, I think that another benefit of adding variance annotations is that you could make your default rules more precise: intW could be a Rule[Int, JsNumber] rather than a Rule[Int, JsValue], etc. If you try to do that now (without variance annotations) you will have a lot of type errors.

If you talk about Write, I mentioned it in my first comment `Write` is already covariant in `O`.

No problem then ?

**Comment by julienrf** [comment]
That’s right.
