### ISSUE TITLE
Sequences stripping out duplicates

### ISSUE THREAD

**Issue by JoeSimmonds** [jto/validation#73]
I recently ran into a problem validating a form containing a list of items.  If the user entered duplicate  values in the list then the validations removed the duplicates.

I think I've tracked the problem down to the toMap call in the spm function here https://github.com/jto/validation/blob/master/validation-form/src/main/scala/Writes.scala#L42  which is removing duplicate keys from the map.

I have a solution for our project which involves our own version of the spm function.

Is my interpretation of this as a problem correct?  If so I'd be happy to prepare a PR with our fix and some tests if that would help.

thanks
    Joe

**Comment by OlivierBlanvillain** [comment]
> Is my interpretation of this as a problem correct?

Yes, this looks like a bug to me. PR welcome!

**Comment by jto** [comment]
Definitely a bug. PR are indeed welcome :)
