### ISSUE TITLE
Upgrade Cats version

### ISSUE THREAD

**Issue by daniel-shuy** [jto/validation#75]
Validation depends on Cats 0.6.0. The latest Cats version (at time of writing) is 0.9.0.

This is a major roadblock to using to using this library, as many other libraries depend on newer versions of Cats, causing incompatibilities among library dependencies.

**Comment by jto** [comment]
Hi Daniel,

I just published validation 2.1.0. It's available for Scala 2.11.8 and 2.12.2. The cats version is 0.9.0.
Enjoy :)

**Comment by daniel-shuy** [comment]
Wow, thanks so much!

I just want to say that this is such a great library. It is the main reason for me to use ScalaJS CrossProjects :)
