### ISSUE TITLE
Validate XML : error on elem disapeared with Node

### ISSUE THREAD

**Issue by gbersac** [jto/validation#76]
I stumbled upon a puzzling error. With a `From[Elem]` in this code :

```scala
case class Commentaire(
  codeMessage: Option[String],
  libelleMessage: String,
  codePriorite: Option[String]
)

object Commentaire {
  implicit val messageRule: Rule[Elem, Commentaire] = From[Elem] { __ =>
    import jto.validation.xml.Rules._

    (
      (__ \ "DossEtude"  \ "codeMessage").read[Option[String]] ~
      (__ \ "DossEtude" \ "libelleMessage").read[String] ~
      (__ \ "DossEtude" \ "prioriteMessage").read[Option[String]]
    )(Commentaire.apply _)
  }

}
```

I got the following error :

```
[error] /Users/gbe/projects/nfc-nb/commons/server/src/main/scala/models/OMDEMessage.scala:92: No implicit view available from jto.validation.Path => jto.validation.RuleLike[scala.xml.Elem,Option[String]].
[error]       (__ \ "DossEtude" \ "codeMessage").read[Option[String]] ~
```

This error disepeared when I replaced `Elem` by `Node` :

```scala
object Commentaire {
  implicit val fmt = Json.format[Commentaire]

  implicit val messageRule: Rule[Node, Commentaire] = From[Node] { __ =>
    (
      (__ \ "DossEtude" \ "codeMessage").read[Option[String]] ~
      (__ \ "DossEtude" \ "libelleMessage").read[String] ~
      (__ \ "DossEtude" \ "prioriteMessage").read[Option[String]]
    )(Commentaire.apply _)
  }

}
```

Whether this library should completely support `Elem` or the user should be notified that the type `Elem` is not supported by this library.

**Comment by OlivierBlanvillain** [comment]
The only thing we could do here is improve the error message. Indeed, the library does support `Elem`! You would just need to implement a few type class instances for this type (as the error suggests), see [this section](http://jto.github.io/validation/docs/book/ScalaValidationExtensions.html) of the doc.

For better error messages, we would need to replace usages of `Function1[A, B]` with an equivalant custom type (`ValidationView[A, B]` or something), and annotate it with an `@implicitNotFound`.

**Comment by jto** [comment]
Thanks for reporting this.

Creating a new type `ValidationView` would break compatibility so maybe for validation v3 but not in v2. We could maybe however support `Elem` too.
As always, PR are welcome @gbersac :)

BTW, there's an extensive test suite [here](https://github.com/jto/validation/blob/master/validation-xml/src/test/scala/RulesSpec.scala) that may help if you need examples of XML validation.
