### ISSUE TITLE
Validating string as numbers

### ISSUE THREAD

**Issue by mycaule** [jto/validation#79]
Please provide Rules implementing the parsing of strings as numbers following this pattern :

`def convert[A](str: String): Option[A]` where A = `Int`, `Long`, `Double`, _etc._ avoiding `NumberFormatException`.

The goal would be to be able to deserialise that type of data
```
{
   "description": "candy",
    "price": {
      "currency": "EUR",
      "value": "3.0000"
    }
}
```

defining the required type in the parsing `Rule` with calls as simple as :
```
case class Item(description: String, price: Double, currency: String)

val itemReader: Rule[JsValue, Item] = From[JsValue] { __ =>
  (
    (__ \ "description").read[String].map(PrivateDealId) ~
    (__ \ "name").read[String] ~
    (__ \ "price" \ "currency").read[String] ~
    (__ \ "price" \ "value").read[Double] // or read[Option[Double]]
  )(Item.apply _)                         // or read(stringToDoubleR)
}
```

Thanks.

### References
[Scala Cookbook - How to convert a String to an Int](http://alvinalexander.com/scala/how-cast-string-to-int-in-scala-string-int-conversion)
[Scala Cookbook - How to parse a number from a String](http://alvinalexander.com/scala/how-to-parse-number-int-long-float-bigint-from-string-in-scala)

**Comment by jto** [comment]
I think it makes sense for String to Bigdecimal, not so for other Numeric types. 
Do you want to make a PR ?
