### ISSUE TITLE
ValidationErrors class?

### ISSUE THREAD

**Issue by stanch** [jto/validation#8]
I’m using something like this to report multiple validation errors:
```scala
case class ValidationErrors(paths: Seq[(Path, Seq[ValidationError])])
  extends Exception(paths.toString())

def throwValidationErrors[O](va: VA[O]) = va recoverTotal {
  case play.api.data.mapping.Failure(paths) ⇒ throw ValidationErrors(paths)
}
```

Maybe you could include a similar API in the project?

**Comment by jto** [comment]
I'm closing the issue since the soon to be published [v2.0](https://github.com/jto/validation/tree/v2.0) now uses cats' `Valid` / `Invalid`.
